service: newschatbot-backend

plugins:
  - serverless-python-requirements
  - serverless-wsgi
custom:
  wsgi:
    app: app/main.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.6
  memorySize: 256
  timeout: 600
  stage: dev
  region: eu-west-3
  vpc:
    securityGroupIds:
      - "sg-0fbabf1fc170b6025"
    subnetIds:
      - "subnet-0bf6b5f75f0c789bf"
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "ec2:CreateNetworkInterface"
          - "ec2:DescribeNetworkInterfaces"
          - "ec2:DetachNetworkInterface"
          - "ec2:DeleteNetworkInterface"
        Resource: "*"
    iamManagedPolicies:
      - "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'