version: '3.0'
services:
    db:
        container_name: postgres
        image: postgres
        restart: always
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: feed_parser
        ports:
          - "5432:5432"